### ISSUE TITLE
Time dilation and overtime unlock reqs WAY too grindy.

### ISSUE THREAD

**Issue by Prezombie** [eternaldensity/Sandcastle-Builder#1319]
555 jumps to shortpix is a massive undertaking, especially considering that there's no real hint on how to get safety blanket, time dilation, and overtime, and that the counter isn't preserved during molpy down. Having the previous boost in the safety net > blanket > overtime > Time dilation along with enough resources to buy it should be enough. Maybe have them only unlockable in shortpix, and locked in longpix if not bought.

Additionally, a boost to have flux harvest run automatically for a price right before the ONG would be nice.

**Comment by dfriedenbach** [comment]
Personally, my inclination would be to see if the counter can be made to carry over on Molpy Down.  As it stands currently, it's a fairly annoying grind but imo not particularly egregious unless you want to MD later.

**Comment by Prezombie** [comment]
Keeping the grind would be fine if it counts across all MDs, but even then, it's a grind with absolutely no hints that it's possible.

**Comment by eternaldensity** [comment]
Agreed, adding a visible counter (to the Doublepost boost) and not
resetting on MD wiukd vastky improve it.

**Comment by zulrang** [comment]
Honestly, you could just add a few Badges as the counter gets higher to drop the hint that it matters.

**Comment by dfriedenbach** [comment]
Okay, so I just started digging into the code recently.  I've looked at Molpy.Down() and also found the code that tracks the number of jumps to shortpix with Doublepost.  I see the jumps are tracked using Safety Net's power value.  Would it make more sense to put the counter in that boost's description rather than Doublepost's?  You wouldn't be able to see it until you've unlocked Safety Net but that tends to happen organically, anyways.

As for making it persist through MD, that would work the same way as Kite and Key and Lightning in a Bottle, just two additional lines of code.  I'll probably do that first thing in the morning (gonna sleep now).

**Comment by eternaldensity** [comment]
Great, thanks

**Comment by dfriedenbach** [comment]
I just went and coded a solution, then when I was testing it I realized that Safety Net is a chronotech boost.  So, the counter actually already doesn't reset if you have Bag of Jolting... but then, if have have BoJ you're basically done MDing anyways.

**Comment by dfriedenbach** [comment]
Okay, I've also updated the description of Doublepost to display Safety Net's power now.  The only remaining thing to do might be to add the power level needed to unlock the next boost to the description as well.  Do you think that would be a good thing? @eternaldensity

**Comment by eternaldensity** [comment]
Knowledge is power, France is bacon.

I mean, yes.

**Comment by dfriedenbach** [comment]
Okay, I submitted a pull request with the fix for this.  Doublepost's description remains the same but in stats view it display's safety net's current power and the power needed to unlock the next boost, if applicable.

I also discovered, while testing, that Wooly Jumper completely trivializes this grind.  The initial 50 jumps for Safety Blanket are still somewhat annoying (I cheated and manually set the power when testing so as to skip most of that), but once you have that, you can just spam click on any shortpix NP, and it will continue to rack up "jumps" even though the NP isn't changing.  If you use key clicks and hold the keys down to spam clicks, you can rack up 500 jumps in well under a minute (maybe 15 seconds).

Of course, that would mean waiting until you're well into the dragon grind in order to get overtime/time dilation.

**Comment by OtherMike** [comment]
Even without Wooly Jumper, this only takes half an hour to an hour, as long as you have Mario and Robotic shopper: set Mario to open 5 QQubes per mNP, set the shopper to buy doublepost always, and time travel from 241 -> 240 -> 241, pause for the tick, and repeat.  The only clicks you need are on time travel, once back, once forward per mNP, since Mario and the shopper should take care of buying doublepost each time.  Once you get the second Safety boost, turn off Mario and the shopper, and just jump back and forth until overtime and time dilation show up.

The last couple times I Molpied Down, that "grind" was a welcome diversion from the much longer grind to max out CDSP, so I could unlock the Fading again and get back to trying to hit its 1.8 second per hour window with as many clicks as possible.
