### ISSUE TITLE
Safety Net power through multiple Molpy Downs

### ISSUE THREAD

**Issue by ThomasBoby** [eternaldensity/Sandcastle-Builder#1331]
If you Molpy Down before you happen to unlock Safety Net you lose your built up power.

This is because the function checks whether you *have* Safety Net, not if the power is non-zero. This might be intentional, but unlike the Lightning boosts it's a lot less obvious you have to trigger Safety Net once or you'll lose the power you can't see!

**Comment by eternaldensity** [comment]
Yeah that's a bit of a problem.

**Comment by dfriedenbach** [comment]
This was intentional on my part, as I was following the precedent set with Kite and Key and Lightning in a Bottle.  It would be fairly trivial to change, though.  The only question is whether to even bother checking if the current power is > 0.  The effect should be the same unless you somehow manage to mustardize Safety Net power.  I don't think that's even possible, but it couldn't hurt to be safe.

**Comment by dfriedenbach** [comment]
In retrospect, I could have phrased the commit message better.
