### ISSUE TITLE
Italian Plumber/Mario slowdown/dead-end

### ISSUE THREAD

**Issue by Calamitizer** [eternaldensity/Sandcastle-Builder#1334]
This is basically a re-opening of issue #928, but I think this could use revisiting. The downgrade button helped, but it's more of a workaround than a solution (the problem being that IP still caused slowdown). Making Shadow Ninja require IP be off feels sort of contrived, and either way, SN eventually becomes something you don't need on 24/7, so it no longer de-incentivizes running IP.

In pretty much every other context in the game, there's a reward for getting any number you have control over as high as possible. A common response to IP slowdown is "Why would you need to increase IP that high?" Well, maybe for a boost. Why would you need to grind losing LongPix boosts? Why would you need to grind the total starved/killed dragons? The answer is: Because there's a boost for it. A player might not know that upgrading IP is a *bad* thing, not a good thing. Upgrading IP is nice and obvious (there's a button for it), whereas something like Molpy.Boosts['DQ'].totalstarves isn't obvious at all. I don't think we want to punish players for clicking an "Upgrade" button in an incremental game; they have no way to know that this upgrade button has negative consequences.

Plus, I did actually have a use for high IP levels: Discovery grinding. I was aware of the slowdown problems, so I cautiously upgraded IP to the point at which I started to notice slowdown (1500 Q/mNP for my computer) and then still had to let it open vaults for a couple hours to get the last couple hundred discoveries.

I think this problem is a prime place for growth of the game! There are a couple of approaches I can think of:

A) Introducing a cap. I don't like this because, as Waveney said in #928, the limits of different computers are different; my computer could apparently handle much more than most, but I appreciated being able to run higher IP, and I would have been somewhat frustrated by a lower cap.

B) Modeling the results, as is (I think?) already done for vaults. My ignorance is explained below =P

C) Changing the functionality of IP. Maybe there's a boost you can unlock that makes it so that, if IP is off, IP *creates* QQs instead of spending them, which would be a reasonable place for the QQ grind to go, I think. This incentivizes turning off IP eventually, however, it doesn't really address the slowdown problem (for the reasons stated in A). E.g. I still would have wanted to open 1500 Q/mNP for a while.

I'd heavily lean towards B. I think putting in place an infrastructure for opening a lot of qubes at once would be pretty great, because (as stated in #928), after finding all the discoveries, there isn't much of a reason to leave IP open. Instead of letting that fact de-incentivize reworking IP, we can let fixing IP incentivize expanding QQ content.

Maybe leaving IP on becomes a way to process/convert QQs into a new Stuff, i.e. QQs opened by Mario have a small chance to contain something like a mushroom. This could maybe be used for Dragon fights (maybe mechanically doubling the stats of the dragons you fledge or something, slowly inching Lords toward the realm of possibility). Maybe just coins, although I think that's too similar flavor-wise to Gold. Maybe fire flowers for boosting breath attacks, when they're a thing.

Regarding option B, what's the name for it? It's probably a really common approach, but I don't know what to call it. For example, say there's a "Coin" boost with a "Flip" boost that either gives you one Head stuff or one Tails stuff each time. Say you upgrade Coin so that clicking the button flips 10,000,000 times now. Evaluating Molpy.Flip() 10,000,000 might cause severe slowdown (okay, it's simple enough that not really), but a better way to do it is to give the player 5,000,000 Heads, plus/minus a fudge factor based on the standard deviation, and then give 10,000,000 - (Heads) Tails. What's the name for this concept of using a model of the distribution to compute an average result over a large number of trials?

So in the context of IP, let's say IP opens N Q/mNP. It seems like it would need to first check whether key/vault autobuy is on. If it is, then basically all the QQs would go into vaults, right? So you just get N/5 vaults. If the autobuys are off, it mostly goes into Greased Lightning, along with ASHF, right? The code for Logicats/Vaults/QQs is still pretty obtuse to me, which is why I'm primarily asking about the feasibility of this sort of caching.

Also, maybe another boost lets you get ASHF while you already have it, letting you just refresh the cooldown, effectively having it forever. Most players already buy everything at a discount since ASHF is functionally on-demand. This means that running IP gives a permanent discount (maybe it gets up to infinity like TD, but that seems pretty pointless).

Anyway, I'm trying to get into development, but I'm still learning how to actually code in JS. So apologies if I'm overstepping, or if I don't realize that something I'm suggesting is unrealistic. I'm just trying to sort of field out how development happens and how ideas are come up with. I've always wanted to have a more active role in the game, since I love it so much. =D

**Comment by pickten** [comment]
Yeah, in general the system isn't great at multi-things like IP. Notifications, for example. But I will look into fixing IP at some point if I have time. Still, I think it would be simpler to run the current version of the randomizer once per IP level if IP<100, or 100 times otherwise (scaling the values as necessary). It's also what I would do for the flipping. It is a good thought to get the distribution and taking it from that. The reason I wouldn't is that it's probably overkill for anything that doesn't require strong precision and may well be slower.

With regards to your last paragraph, there's no such thing as overstepping by suggesting fixes for legitimate problems, and this is probably doable.

**Comment by LuminousLeopards** [comment]
Feel free to have at it, but it might be kind of involved for a first project. What causes the slowdown is Molpy.RewardLogicat() which pushes rewards to an array via a For loop that searches through Molpy.Boosts (so this actually gets less efficient as boosts are added). What rewards are available is what would be difficult to get without a loop, since the conditions vary based on the particular boost, logicat level, and what's currently unlocked. But I definitely haven't looked at it that intensively, and I agree that it would be great to be able to upgrade Mario to open 2 million QQs and not have to worry about resource utilization. If you do figure out a way to do it, you could also look at Molpy.FindThings() in dragons.js--it uses the same exact logic.

Also I'd ask if you're going to add a boost that's going to affect QQs or Logicat levels substantially please let me know first, since it would affect the current late-stage game and I have plans for Logicat stuff.

Notifications take basically no resources as far as I've been able to tell. If they're jagging it's likely because other things are eating CPU or memory.

**Comment by pickten** [comment]
I hadn't realized notifs were efficient. I guess the lag issues were logicats (IP only around 5-10).

Anyways, I think it should be relatively simple to fix the IP issue, assuming logicat boost multiproc is a thing. By what Calamatizer said, vault keys/vaults can already be multibought (is that actually right?). I can't really think of much that'd be affected by appearing multiple times except duration, and I'd assume 500-750 IP runs (the slowdown isn't noticeable until around 1500, correct?) is plenty enough for that to cap out, especially if IP is left running.

I'll start working on it later today. I don't think anything serious will change besides IP/FindThings handling speed (i.e. no planned boost), but it might be nice to have achievements (maybe one for IP 1000?).

If I have some more time afterwards, I'll also try to improve the logic so the efficiency loss is only as the number of logicat/dragon boosts grows, but that would be harder. By the way, what are the dragon versions of the logicat functions (FindThings is one, is there any other I should know about)?


The basic plan is as I said earlier, wherein IP/FindThings runs some reasonable number of times and scales to match, so that the logic itself is essentially unchanged. If I do the better version (the logic improvement), my plan is to try to generate the list of logic/dragon boosts (all that can ever be obtained from them) on window load, and then iterating over those only. Since that list is much smaller, RewardLogicat should be correspondingly faster.

**Comment by LuminousLeopards** [comment]
Cool, feel free to PM me on Reddit if you need anything.

**Comment by Calamitizer** [comment]
That's awesome! I had been looking at Molpy.RewardLogicat() for a while, but I wasn't parsing what was happening very well once I traced it back to Molpy.RewardRedacted(). I did have a couple thoughts, though. I'll have to wait and see what approach you're using to refactor it to really be able to contribute to that discussion. 

I'm in a place where I'm not really confident in my ability to actually accomplish much, but I've been looking over the code for a few hours now and it's starting to make a lot more sense. Like LL said, a project involving full comprehension of DoRD/Logicat code is very... involved. I'm trying to figure out something a little simpler that needs doing =p any suggestions on an issue tag I could mess around with to understand the code better?

**Comment by Calamitizer** [comment]
obviously I am still learning github as well. >>

**Comment by LuminousLeopards** [comment]
Hmm, not off the top of my head...I tend to cherry-pick the easy ones :P Maybe #1310 and #1332, most of the other issues should actually be closed at this point.

I'd recommend just downloading the zip of the repository and using an IDE like Sublime Text 2 to open the whole folder. Read Ye API.md and then just look through a bunch of boosts; most of the standard boost functions are really straightforward (guess what Molpy.UnlockBoost does). For dragons, combat and related stuff flows from Molpy.DragonKnightAttack(), figuring out atk/def/dig etc follow from Molpy.Liner() and Molpy.DragonFledge(). Just look through the flow of functions called and you'll be able to follow the logic.
