### ISSUE TITLE
Classic broken with cloud sync

### ISSUE THREAD

**Issue by elswyyr** [eternaldensity/Sandcastle-Builder#1390]
When attempting to run Classic.html, it fails with the error message "ReferenceError: GH is not defined options.js:134:4". Seems to be something related to cloud sync, but I don't know how that part of the code works.

**Comment by erp-lsf** [comment]
That's my part of the code. I'll try to look at it ASAP, thanks.

**Comment by EPSIL0N** [comment]
I think we ran into the same in the LL testing branch and the issue was as simple as:

<script src="masterpiece.js?v=1"></script> /classic,html ends here
<script src="github.js?v=1"></script>
<script src="gh.js?v=1"></script> /these two are added to castle.html

but I play with a layout so I can't say I tested much beyond it actually loading up and I don't think I've ever actually used the gh synch in either style.

**Comment by elswyyr** [comment]
Seems to be working after EPSIL0N's 4.0 pull.
