### ISSUE TITLE
Molpy.PokeBar uses CDSP's power, not bought level

### ISSUE THREAD

**Issue by D0rako** [eternaldensity/Sandcastle-Builder#1429]
Among other things this makes CDSP impossible to downgrade since CDSP also uses PokeBar to check the level of the thing.

**Comment by IHaveNoFunnyName** [comment]
Pokebar is fine, power should be CDSP's current power and bought should be highest achieved. I think. Reading CDSP seems this way as if bought is higher than power, upgrading is free, and I remember it being that way from when I went though this stage around a year ago.

I think the problem is in Molpy.GainDragonWisdom, when downgrading bought is effected and power isn't. It should be the other way around. When I change that I can downgrade properly.

**Comment by D0rako** [comment]
Damn must've mixed the two up. Not that I've seen the v4 stuff either but I think CDSP's capped by then anyway. Closing the issue and hopefully it doesn't show up after the next patch.
